/**
 * `buffer/stream.ts`
 * - Provider-neutral GenAI stream buffering primitives.
 *
 * @origin eureka-agents-api / src/lib/buffer/stream.ts
 *
 * Common stream buffering primitives for GenAI providers.
 *
 * This module is intentionally provider-neutral. Gemini/OpenAI adapters can
 * convert their native stream chunks into GenAIStreamEvent and let this buffer
 * handle batching, FIFO ordering, and progress calculation.
 */

export type GenAIStreamKind = 'text' | 'json' | 'image' | 'binary' | 'unknown';

export type GenAIStreamFlushStrategy = 'size' | 'time' | 'bytes' | 'hybrid';

export interface GenAIStreamEstimate {
    /** expected generated character count, if known or estimated */
    totalChars?: number;
    /** expected generated byte count, if known or estimated */
    totalBytes?: number;
    /** expected generated token count, if known or estimated */
    totalTokens?: number;
    /** where the estimate came from, e.g. maxOutputTokens, sample, imageSize */
    source?: string;
    /** true when the value is inferred rather than exact */
    estimated?: boolean;
    /** optional confidence in [0, 1] */
    confidence?: number;
}

export interface GenAIStreamProgress {
    loadedChars: number;
    loadedBytes: number;
    loadedTokens?: number;
    totalChars?: number;
    totalBytes?: number;
    totalTokens?: number;
    /** stream-total progress from chars/bytes/tokens estimates, if available */
    percent?: number;
    /** buffer-cycle progress, always present while the buffer can estimate it */
    bufferPercent?: number;
    /** buffer-cycle progress source */
    source?: 'chunk' | 'interval' | 'flush' | 'eof' | 'snapshot';
    pendingChunks?: number;
    pendingBytes?: number;
    pendingChars?: number;
    bufferElapsedMs?: number;
    bufferTargetChunks?: number;
    bufferTargetBytes?: number;
    bufferTargetMs?: number;
    estimated: boolean;
}

export interface GenAIStreamMeta {
    provider?: string;
    model?: string;
    kind?: GenAIStreamKind;
    estimate?: GenAIStreamEstimate;
    [key: string]: any;
}

export interface GenAIStreamEventBase {
    id?: string;
    index?: number;
    createdAt?: number;
    meta?: GenAIStreamMeta;
}

export interface GenAIStreamStartEvent extends GenAIStreamEventBase {
    type: 'start';
    estimate?: GenAIStreamEstimate;
}

export interface GenAIStreamChunkEvent extends GenAIStreamEventBase {
    type: 'chunk';
    data: string;
    chars?: number;
    bytes?: number;
    tokens?: number;
    progress?: GenAIStreamProgress;
}

export interface GenAIStreamFlushEvent extends GenAIStreamEventBase {
    type: 'flush';
    data: string;
    chunks: GenAIStreamChunkEvent[];
    count: number;
    chars: number;
    bytes: number;
    progress: GenAIStreamProgress;
}

export interface GenAIStreamProgressEvent extends GenAIStreamEventBase {
    type: 'progress';
    progress: GenAIStreamProgress;
}

export interface GenAIStreamEofEvent extends GenAIStreamEventBase {
    type: 'eof';
    progress: GenAIStreamProgress;
}

export interface GenAIStreamErrorEvent extends GenAIStreamEventBase {
    type: 'error';
    error: any;
}

export type GenAIStreamEvent =
    | GenAIStreamStartEvent
    | GenAIStreamChunkEvent
    | GenAIStreamFlushEvent
    | GenAIStreamProgressEvent
    | GenAIStreamEofEvent
    | GenAIStreamErrorEvent;

export interface GenAIStreamConsumer {
    (event: GenAIStreamEvent): Promise<void> | void;
}

export interface GenAILegacyTokenConsumer {
    (token?: string | null): Promise<void> | void;
}

export interface GenAIStreamBufferOptions {
    /** disable buffering and flush every chunk immediately */
    useBuffer?: boolean;
    /** size: count, time: timer, bytes: bytes, hybrid: any condition */
    flushStrategy?: GenAIStreamFlushStrategy;
    /** chunk count threshold */
    bufferSize?: number;
    /** byte threshold */
    bufferBytes?: number;
    /** time strategy interval */
    bufferMs?: number;
    /** max wait for size/bytes/hybrid strategies */
    maxWaitMs?: number;
    /** initial stream metadata */
    meta?: GenAIStreamMeta;
    /** emit progress events after each accepted chunk */
    emitProgress?: boolean;
    /** emit current buffer progress on this interval while chunks are pending; 0 disables */
    progressIntervalMs?: number;
    /** emit an error and close the buffer if the stream stays open longer than this; 0 disables */
    timeoutMs?: number;
}

export interface GenAIStreamBufferSnapshot {
    pendingChunks: number;
    pendingChars: number;
    pendingBytes: number;
    loadedChars: number;
    loadedBytes: number;
    loadedTokens?: number;
    closed: boolean;
    progress: GenAIStreamProgress;
}

export interface GenAIMockStreamOptions {
    kind?: GenAIStreamKind;
    provider?: string;
    model?: string;
    chunkSize?: number;
    intervalMs?: number;
    estimate?: GenAIStreamEstimate;
}

const DEFAULT_OPTIONS: Required<Omit<GenAIStreamBufferOptions, 'meta'>> = {
    useBuffer: true,
    flushStrategy: 'hybrid',
    bufferSize: 10,
    bufferBytes: 16 * 1024,
    bufferMs: 300,
    maxWaitMs: 300,
    emitProgress: false,
    progressIntervalMs: 0,
    timeoutMs: 0,
};

const now = () => Date.now();

const textEncoder = new TextEncoder();
const byteLength = (value: string): number => textEncoder.encode(value).length;

const asPercent = (loaded: number, total?: number): number | undefined => {
    if (!total || total <= 0) return undefined;
    return Math.max(0, Math.min(100, Math.floor((loaded / total) * 100)));
};

/**
 * Estimate text output size from common generation hints.
 */
export const estimateGenAIStreamSize = (hint?: {
    kind?: GenAIStreamKind;
    maxOutputTokens?: number;
    maxTokens?: number;
    totalChars?: number;
    totalBytes?: number;
    totalTokens?: number;
    imageSize?: '1k' | '2k' | '4k' | string;
    imageFormat?: 'png' | 'jpeg' | 'jpg' | 'webp' | string;
}): GenAIStreamEstimate | undefined => {
    if (!hint) return undefined;
    if (hint.totalChars || hint.totalBytes || hint.totalTokens) {
        return {
            totalChars: hint.totalChars,
            totalBytes: hint.totalBytes,
            totalTokens: hint.totalTokens,
            estimated: false,
            source: 'explicit',
            confidence: 1,
        };
    }

    const maxTokens = hint.maxOutputTokens ?? hint.maxTokens;
    if (maxTokens && maxTokens > 0) {
        const totalChars = maxTokens * 4;
        return {
            totalChars,
            totalBytes: totalChars,
            totalTokens: maxTokens,
            estimated: true,
            source: 'maxOutputTokens',
            confidence: 0.45,
        };
    }

    if (hint.kind === 'image' && hint.imageSize) {
        const normalized = `${hint.imageSize}`.toLowerCase();
        const megapixels = normalized.includes('4k') ? 8 : normalized.includes('2k') ? 3 : 1;
        const format = `${hint.imageFormat ?? 'png'}`.toLowerCase();
        const bytesPerMegapixel =
            format === 'webp' ? 350_000 : format === 'jpeg' || format === 'jpg' ? 500_000 : 900_000;
        return {
            totalBytes: megapixels * bytesPerMegapixel,
            estimated: true,
            source: 'imageSize',
            confidence: 0.25,
        };
    }

    return undefined;
};

/**
 * FIFO stream buffer. Chunk events are queued and flushed as a single `flush`
 * event when size/time/byte conditions are met.
 */
export class GenAIStreamBuffer {
    private readonly options: Required<Omit<GenAIStreamBufferOptions, 'meta'>>;
    private readonly meta?: GenAIStreamMeta;
    private queue: GenAIStreamChunkEvent[] = [];
    private timer?: ReturnType<typeof setTimeout>;
    private progressTimer?: ReturnType<typeof setInterval>;
    private timeoutTimer?: ReturnType<typeof setTimeout>;
    private processing = false;
    private closed = false;
    private index = 0;
    private loadedChars = 0;
    private loadedBytes = 0;
    private loadedTokens = 0;
    private estimate?: GenAIStreamEstimate;
    private cycleStartedAt?: number;
    private lastProgress?: GenAIStreamProgress;

    constructor(private readonly consumer: GenAIStreamConsumer, options?: GenAIStreamBufferOptions) {
        this.options = { ...DEFAULT_OPTIONS, ...(options ?? {}) };
        this.meta = options?.meta;
        this.estimate = options?.meta?.estimate;
    }

    public async start(meta?: GenAIStreamMeta): Promise<void> {
        this.ensureOpen();
        this.estimate = meta?.estimate ?? this.estimate;
        this.scheduleTimeout();
        await this.consumer({
            type: 'start',
            index: this.index++,
            createdAt: now(),
            meta: { ...this.meta, ...(meta ?? {}) },
            estimate: this.estimate,
        });
    }

    public async write(data: string, meta?: GenAIStreamMeta & { tokens?: number }): Promise<void> {
        await this.push({
            type: 'chunk',
            data,
            tokens: meta?.tokens,
            meta: { ...this.meta, ...(meta ?? {}) },
        });
    }

    public async push(event: string | GenAIStreamEvent): Promise<void> {
        this.ensureOpen();
        this.scheduleTimeout();
        const normalized = typeof event === 'string' ? this.asChunk(event) : this.normalizeEvent(event);

        if (normalized.type === 'chunk') {
            await this.enqueue(normalized);
            return;
        }

        if (normalized.type === 'start') {
            this.estimate = normalized.estimate ?? normalized.meta?.estimate ?? this.estimate;
        }
        if (normalized.type === 'eof') {
            await this.close();
            return;
        }
        if (normalized.type === 'error') {
            await this.reportError(normalized.error, 'upstream-error');
            return;
        }
        await this.consumer(normalized);
    }

    public async flush(): Promise<void> {
        if (this.processing || this.queue.length === 0) return;
        this.processing = true;
        this.clearTimer();
        this.clearProgressTimer();
        const chunks = this.queue;

        const data = chunks.map(chunk => chunk.data).join('');
        const chars = chunks.reduce((sum, chunk) => sum + (chunk.chars ?? chunk.data.length), 0);
        const bytes = chunks.reduce((sum, chunk) => sum + (chunk.bytes ?? byteLength(chunk.data)), 0);
        const progress = this.progress('flush', 100);
        this.queue = [];
        this.cycleStartedAt = undefined;

        try {
            await this.consumer({
                type: 'flush',
                index: this.index++,
                createdAt: now(),
                meta: this.meta,
                data,
                chunks,
                count: chunks.length,
                chars,
                bytes,
                progress,
            });
        } finally {
            this.processing = false;
        }

        if (this.queue.length > 0) {
            if (!this.options.useBuffer || this.shouldFlush()) {
                await this.flush();
            } else {
                this.scheduleFlush();
                this.scheduleProgress();
            }
        }
    }

    public async close(): Promise<void> {
        if (this.closed) return;
        await this.flush();
        this.clearTimer();
        this.clearProgressTimer();
        this.clearTimeout();
        this.closed = true;
        await this.consumer({
            type: 'eof',
            index: this.index++,
            createdAt: now(),
            meta: this.meta,
            progress: this.progress('eof', 100),
        });
    }

    public async cancel(reason?: any): Promise<void> {
        if (this.closed) return;
        await this.reportError(reason ?? 'GenAIStreamBuffer canceled', 'cancel');
    }

    public snapshot(): GenAIStreamBufferSnapshot {
        const pendingChars = this.queue.reduce((sum, chunk) => sum + (chunk.chars ?? chunk.data.length), 0);
        const pendingBytes = this.queue.reduce((sum, chunk) => sum + (chunk.bytes ?? byteLength(chunk.data)), 0);
        return {
            pendingChunks: this.queue.length,
            pendingChars,
            pendingBytes,
            loadedChars: this.loadedChars,
            loadedBytes: this.loadedBytes,
            loadedTokens: this.loadedTokens || undefined,
            closed: this.closed,
            progress: this.closed && this.lastProgress ? this.lastProgress : this.progress('snapshot'),
        };
    }

    private async enqueue(chunk: GenAIStreamChunkEvent): Promise<void> {
        if (!this.cycleStartedAt) this.cycleStartedAt = now();
        const normalized = this.normalizeChunk(chunk);
        this.loadedChars += normalized.chars ?? normalized.data.length;
        this.loadedBytes += normalized.bytes ?? byteLength(normalized.data);
        this.loadedTokens += normalized.tokens ?? 0;

        this.queue.push(normalized);
        normalized.progress = this.progress('chunk');

        if (this.options.emitProgress) {
            await this.emitProgress('chunk');
        }

        if (!this.options.useBuffer || this.shouldFlush()) {
            await this.flush();
            return;
        }
        this.scheduleFlush();
        this.scheduleProgress();
    }

    private normalizeEvent(event: GenAIStreamEvent): GenAIStreamEvent {
        return {
            ...event,
            index: event.index ?? this.index++,
            createdAt: event.createdAt ?? now(),
            meta: { ...this.meta, ...(event.meta ?? {}) },
        } as GenAIStreamEvent;
    }

    private normalizeChunk(event: GenAIStreamChunkEvent): GenAIStreamChunkEvent {
        const data = event.data ?? '';
        return {
            ...event,
            type: 'chunk',
            data,
            chars: event.chars ?? data.length,
            bytes: event.bytes ?? byteLength(data),
            index: event.index ?? this.index++,
            createdAt: event.createdAt ?? now(),
            meta: { ...this.meta, ...(event.meta ?? {}) },
        };
    }

    private asChunk(data: string): GenAIStreamChunkEvent {
        return this.normalizeChunk({ type: 'chunk', data });
    }

    private progress(
        source: GenAIStreamProgress['source'] = 'snapshot',
        forcedBufferPercent?: number,
    ): GenAIStreamProgress {
        const totalChars = this.estimate?.totalChars;
        const totalBytes = this.estimate?.totalBytes;
        const totalTokens = this.estimate?.totalTokens;
        const byChars = asPercent(this.loadedChars, totalChars);
        const byBytes = asPercent(this.loadedBytes, totalBytes);
        const byTokens = asPercent(this.loadedTokens, totalTokens);
        const streamPercent = source === 'eof' ? 100 : byChars ?? byBytes ?? byTokens;
        const bufferProgress = this.bufferProgress(forcedBufferPercent);
        this.lastProgress = {
            loadedChars: this.loadedChars,
            loadedBytes: this.loadedBytes,
            loadedTokens: this.loadedTokens || undefined,
            totalChars,
            totalBytes,
            totalTokens,
            percent: streamPercent,
            bufferPercent: bufferProgress.percent,
            source,
            pendingChunks: bufferProgress.pendingChunks,
            pendingBytes: bufferProgress.pendingBytes,
            pendingChars: bufferProgress.pendingChars,
            bufferElapsedMs: bufferProgress.elapsedMs,
            bufferTargetChunks: bufferProgress.targetChunks,
            bufferTargetBytes: bufferProgress.targetBytes,
            bufferTargetMs: bufferProgress.targetMs,
            estimated: this.estimate?.estimated ?? true,
        };
        return this.lastProgress;
    }

    private bufferProgress(forcedPercent?: number): {
        percent: number;
        pendingChunks: number;
        pendingChars: number;
        pendingBytes: number;
        elapsedMs: number;
        targetChunks?: number;
        targetBytes?: number;
        targetMs?: number;
    } {
        const pendingChunks = this.queue.length;
        const pendingChars = this.queue.reduce((sum, chunk) => sum + (chunk.chars ?? chunk.data.length), 0);
        const pendingBytes = this.queue.reduce((sum, chunk) => sum + (chunk.bytes ?? byteLength(chunk.data)), 0);
        const elapsedMs = this.cycleStartedAt ? Math.max(0, now() - this.cycleStartedAt) : 0;
        const byChunks = asPercent(pendingChunks, this.options.bufferSize) ?? 0;
        const byBytes = asPercent(pendingBytes, this.options.bufferBytes) ?? 0;
        const byBufferMs = asPercent(elapsedMs, this.options.bufferMs) ?? 0;
        const byMaxWaitMs = asPercent(elapsedMs, this.options.maxWaitMs) ?? 0;
        let percent = 0;
        let targetChunks: number | undefined;
        let targetBytes: number | undefined;
        let targetMs: number | undefined;

        if (!this.options.useBuffer) {
            percent = pendingChunks > 0 ? 100 : 0;
        } else if (this.options.flushStrategy === 'size') {
            percent = byChunks;
            targetChunks = this.options.bufferSize;
            targetMs = this.options.maxWaitMs;
        } else if (this.options.flushStrategy === 'bytes') {
            percent = byBytes;
            targetBytes = this.options.bufferBytes;
            targetMs = this.options.maxWaitMs;
        } else if (this.options.flushStrategy === 'time') {
            percent = byBufferMs;
            targetMs = this.options.bufferMs;
        } else {
            percent = Math.max(byChunks, byBytes, byMaxWaitMs);
            targetChunks = this.options.bufferSize;
            targetBytes = this.options.bufferBytes;
            targetMs = this.options.maxWaitMs;
        }

        return {
            percent: forcedPercent ?? Math.max(0, Math.min(99, percent)),
            pendingChunks,
            pendingChars,
            pendingBytes,
            elapsedMs,
            targetChunks,
            targetBytes,
            targetMs,
        };
    }

    private async emitProgress(source: GenAIStreamProgress['source'] = 'snapshot'): Promise<void> {
        if (this.closed) return;
        await this.consumer({
            type: 'progress',
            index: this.index++,
            createdAt: now(),
            meta: this.meta,
            progress: this.progress(source),
        });
    }

    private shouldFlush(): boolean {
        const chunks = this.queue.length;
        const bytes = this.queue.reduce((sum, chunk) => sum + (chunk.bytes ?? byteLength(chunk.data)), 0);
        if (this.options.flushStrategy === 'size') return chunks >= this.options.bufferSize;
        if (this.options.flushStrategy === 'bytes') return bytes >= this.options.bufferBytes;
        if (this.options.flushStrategy === 'time') return false;
        return chunks >= this.options.bufferSize || bytes >= this.options.bufferBytes;
    }

    private scheduleFlush(): void {
        if (this.timer) return;
        const waitMs = this.options.flushStrategy === 'time' ? this.options.bufferMs : this.options.maxWaitMs;
        this.timer = setTimeout(async () => {
            await this.flush();
        }, waitMs);
    }

    private scheduleProgress(): void {
        if (!this.options.progressIntervalMs || this.progressTimer || this.queue.length === 0) return;
        this.progressTimer = setInterval(() => {
            if (this.closed || this.queue.length === 0) {
                this.clearProgressTimer();
                return;
            }
            void this.emitProgress('interval').catch(err => this.reportError(err, 'progress-consumer-error'));
        }, this.options.progressIntervalMs);
    }

    private scheduleTimeout(): void {
        if (!this.options.timeoutMs || this.timeoutTimer) return;
        this.timeoutTimer = setTimeout(() => {
            void this.reportError(
                {
                    code: 'GENAI_STREAM_BUFFER_TIMEOUT',
                    message: `GenAIStreamBuffer timed out after ${this.options.timeoutMs}ms`,
                    timeoutMs: this.options.timeoutMs,
                },
                'timeout',
            );
        }, this.options.timeoutMs);
    }

    private clearTimer(): void {
        if (!this.timer) return;
        clearTimeout(this.timer);
        this.timer = undefined;
    }

    private clearProgressTimer(): void {
        if (!this.progressTimer) return;
        clearInterval(this.progressTimer);
        this.progressTimer = undefined;
    }

    private clearTimeout(): void {
        if (!this.timeoutTimer) return;
        clearTimeout(this.timeoutTimer);
        this.timeoutTimer = undefined;
    }

    private async reportError(
        error: any,
        reason: 'cancel' | 'timeout' | 'upstream-error' | 'progress-consumer-error',
    ): Promise<void> {
        if (this.closed) return;
        this.clearTimer();
        this.clearProgressTimer();
        this.clearTimeout();
        this.closed = true;
        const normalized =
            error instanceof Error
                ? { name: error.name, message: error.message, stack: error.stack, reason }
                : typeof error === 'object' && error
                ? { ...error, reason }
                : { message: `${error}`, reason };
        await this.consumer({
            type: 'error',
            index: this.index++,
            createdAt: now(),
            meta: this.meta,
            error: normalized,
        });
    }

    private ensureOpen(): void {
        if (this.closed) throw new Error('GenAIStreamBuffer is already closed');
    }
}

/**
 * Convert a stream-event consumer into the existing token/null consumer shape.
 */
export const asLegacyTokenConsumer = (consumer: GenAIStreamConsumer): GenAILegacyTokenConsumer => {
    const buffer = new GenAIStreamBuffer(consumer, { useBuffer: false });
    return async (token?: string | null) => {
        if (token === null) {
            await buffer.close();
            return;
        }
        if (typeof token === 'string') await buffer.write(token);
    };
};

/**
 * Convert a legacy token consumer into a stream-event consumer.
 */
export const asStreamConsumer = (consumer: GenAILegacyTokenConsumer): GenAIStreamConsumer => {
    return async event => {
        if (event.type === 'flush') {
            await consumer(event.data);
            return;
        }
        if (event.type === 'chunk') {
            await consumer(event.data);
            return;
        }
        if (event.type === 'eof') await consumer(null);
    };
};

/**
 * Create provider-like mock stream events from a text payload.
 */
export async function* mockGenAIStream(
    content: string,
    options?: GenAIMockStreamOptions,
): AsyncGenerator<GenAIStreamEvent, void, unknown> {
    const chunkSize = Math.max(1, options?.chunkSize ?? 16);
    const meta: GenAIStreamMeta = {
        provider: options?.provider ?? 'mock',
        model: options?.model ?? 'mock-model',
        kind: options?.kind ?? 'text',
        estimate:
            options?.estimate ??
            estimateGenAIStreamSize({ totalChars: content.length, totalBytes: byteLength(content) }),
    };
    yield { type: 'start', createdAt: now(), meta, estimate: meta.estimate };
    for (let i = 0; i < content.length; i += chunkSize) {
        if (options?.intervalMs) await new Promise(resolve => setTimeout(resolve, options.intervalMs));
        yield {
            type: 'chunk',
            createdAt: now(),
            meta,
            data: content.substring(i, i + chunkSize),
        };
    }
    yield {
        type: 'eof',
        createdAt: now(),
        meta,
        progress: {
            loadedChars: content.length,
            loadedBytes: byteLength(content),
            totalChars: content.length,
            totalBytes: byteLength(content),
            percent: 100,
            estimated: false,
        },
    };
}

/**
 * Run mock stream events through GenAIStreamBuffer.
 */
export const runMockGenAIStream = async (
    content: string,
    consumer: GenAIStreamConsumer,
    bufferOptions?: GenAIStreamBufferOptions,
    mockOptions?: GenAIMockStreamOptions,
): Promise<GenAIStreamBufferSnapshot> => {
    const buffer = new GenAIStreamBuffer(consumer, bufferOptions);
    for await (const event of mockGenAIStream(content, mockOptions)) {
        await buffer.push(event);
    }
    return buffer.snapshot();
};
